#!/bin/sh
#The script comes from nasyun.com that is the cloud forum Mojelly, which is convenient for black Q players to extract the original patch related files in the RAM DISK of each model,
#Drive files, model configuration and other QTS system files are only used to learn and understand Linux-related technical knowledge. It is forbidden to use this script or black Q for any commercial purpose!

#This script by Mojelly to extract initrd from QNAP boot disk, for extracting patch, drivers, model...
#This script is only used to learn and understand Linux related technical knowledge.
#It is forbidden to use it or HackQNAP for any commercial purpose!

extract_initrd()
{
    if ["$1" = "lzma" ]; then
        mv ./initrd.boot ./initrd.boot.lzma
        unlzma ./initrd.boot.lzma
    else
        mv ./initrd.boot ./initrd.boot.gz
        gzip -d ./initrd.boot.gz
    fi
    if [$? != 0 ]; then
        echo "Decompress the ram disk failed."
        rm -f ./initrd.boot.*
        return 1
    fi
    [-d ./initrd] || mkdir ./initrd
    cd ./initrd
    cpio -id <../initrd.boot 1>/dev/null 2>&1
    cd ..
    rm -f ./initrd.boot
}

error_exit()
{
    echo $1
    exit 1
}

WORKING_DIR=$(pwd)

ls *.zip 1>/dev/null 2>&1 || error_exit "No zip file found!"
for i in *.zip

do
if [! -d ${i/.zip/}/initrd ]; then
[-d ${i/.zip/}] || mkdir ./${i/.zip//}
[! -e ${i/.zip/}/${i/.zip/}.img] && unzip $i -d ./${i/.zip//}
[-e ${i/.zip/}/${i/.zip/}.img] || (echo "Error: img firmware file not found!" && echo "ERROR: No ${i/.zip/ }.img file found!")
The
cd ${i/.zip/}
[-e decoded_firmware.tar.gz] || ../pc1 d QNAPNASVERSION4 ./*.img ./decoded_firmware.tar.gz
if [-e decoded_firmware.tar.gz ]; then
rm -f ./${i/.zip/}.img
tar -xvf decoded_firmware.tar.gz initrd.boot
rm -f decoded_firmware.tar.gz
extract_initrd "lzma"
echo "Information: [${i/.zip/}] initrd file extracted successfully!" && echo "INFO: [${i/.zip/}] initrd extract successful."
echo
else
echo "Error: Unable to decrypt ${i/.zip/} firmware!" && echo "ERROR: Unable to decoded QNAP firmware for ${i/.zip/}.img."
echo
fi
The
cd $WORKING_DIR
else
echo "Information: ${i/.zip/} initrd directory already exists! To re-extract, please delete the existing initrd directory first!" && echo "INFO: [${i/.zip/}] initrd directory already exists, If you want to extract the initrd again, delete the existing initrd directory."
echo
fi
done

exit 0